# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://docs.github.com/en/actions/publishing-packages/publishing-nodejs-packages

name: Node.js Package

on:
  push:
    branches: [ npm-jfrog-publish ]
  release:
    types: [created]

jobs:
  publish-jfrog:
    runs-on: ubuntu-latest

    env:
      STAGING_DIR: ./npm_staging
      
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          registry-url: ${{ secrets.JFROG_REGISTRY_URL }}

      - run: |
          echo "Creating package.json needed to npm publish..."
          
          PACKAGE_VERSION=$(echo "${{ github.ref_name }}" | sed 's/^v//')
          
          # Creazione di un package.json minimale
          # Assicurati di SOSTITUIRE 'nome-del-tuo-pacchetto' con il nome NPM corretto!
          cat <<EOF > package.json
          {
            "name": "usablenet-aqapagecapture", 
            "version": "$PACKAGE_VERSION",
            "license": "ISC",
            "files": [
              "plugin.playwright.js",
              "plugin.playwright.d.ts"
            ]
          }
          EOF
          echo "package.json created with version: $PACKAGE_VERSION"
      - run: |
          echo "Processing files for publishing in $STAGING_DIR..."
          mkdir -p $STAGING_DIR
          
          mv package.json $STAGING_DIR/
          
          cp plugin.playwright.js $STAGING_DIR/
          cp plugin.playwright.d.ts $STAGING_DIR/
      - run: npm publish --access public
        working-directory: ${{ env.STAGING_DIR }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JFROG_NPM_TOKEN }}
